### ISSUE TITLE
Container Fails to Start on Synology

### ISSUE THREAD

**Issue by barndawgie** [felddy/weewx-docker#27]
# 🐛 Bug Report

## To Reproduce

Run the following command on a Synology NAS with Docker installed:
`docker run --name "weewx" --restart unless-stopped -d --net=host -e TZ=$TIME_ZONE -e WEEWX_UID=weewx -e WEEWX_GID=dialout --mount type=bind,src=$VOLUME_BASE/weewx/data,dst=/data:Z --mount type=bind,src=$CERT_DIR,dst=/certs:Z -it felddy/weewx:latest`

## Expected behavior

I expect: The container starts up successfully.
Actually: Failure appears int he logs. I think the configuration files are not getting created as the $VOLUME_BASE/weewx/data directory is empty.

## Any helpful log output

Paste the results here:

```bash
Switching uid:gid to weewx:dialout
Nov  5 14:59:24 syslogd started: BusyBox v1.30.1
Nov  5 14:59:27 weewx[18] INFO __main__: Initializing weewx version 4.1.1
Nov  5 14:59:27 weewx[18] INFO __main__: Using Python 3.8.5 (default, Sep 10 2020, 16:58:22)  [GCC 8.3.0]
Nov  5 14:59:27 weewx[18] INFO __main__: Platform Linux-3.10.105-x86_64-with-glibc2.2.5
Nov  5 14:59:27 weewx[18] INFO __main__: Locale is 'C.UTF-8'
Nov  5 14:59:27 weewx[18] INFO __main__: Using configuration file /data/weewx.conf
Nov  5 14:59:27 weewx[18] INFO __main__: Debug is 0
Nov  5 14:59:27 weewx[18] CRITICAL __main__: Caught unrecoverable exception:
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****  'unspecified'
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****  Traceback (most recent call last):
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****    File "./bin/weewxd", line 148, in main
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 69, in __init__
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****      self.setupStation(config_dict)
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 87, in setupStation
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****      driver = config_dict[station_type]['driver']
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****    File "/opt/venv/lib/python3.8/site-packages/configobj.py", line 554, in __getitem__
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****      val = dict.__getitem__(self, key)
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****  KeyError: 'unspecified'
Nov  5 14:59:27 weewx[18] CRITICAL __main__:     ****  Exiting.
Traceback (most recent call last):
  File "./bin/weewxd", line 261, in <module>
    main()
  File "./bin/weewxd", line 148, in main
    engine = weewx.engine.StdEngine(config_dict)
  File "/home/weewx/bin/weewx/engine.py", line 69, in __init__
    self.setupStation(config_dict)
  File "/home/weewx/bin/weewx/engine.py", line 87, in setupStation
    driver = config_dict[station_type]['driver']
  File "/opt/venv/lib/python3.8/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'unspecified'
```

**Comment by barndawgie** [comment]
If I try this using docker-compose instead (or without the :Z after the paths) I see:
```bash
barndawgie@barndawgserver:/volume1/docker/weewx$ docker-compose run weewx
Creating volume "weewx_data" with default driver
Switching uid:gid to weewx:dialout
Creating a configration file on the container data volume.
Nov  5 18:13:55 syslogd started: BusyBox v1.30.1
cp: cannot create regular file '/data/weewx.conf': Permission denied
```

Which I think means there is potentially some SELinux permissions issue.

I see this even adding `--privileged` to my docker run.

**Comment by felddy** [comment]
I believe that the Synology Docker implementation has "blessed" locations that bind mounts may exists.  I'm not sure what those locations are, but I would try moving the volume to this blessed location.

**Comment by ksperow** [comment]
I ran into the same issue, but you can resolve this permission issue by opening up the permissions on $VOLUME_BASE/weewx/data.

chmod 775 $VOLUME_BASE/weewx/data

Ideally, the permissions as defined within synology for the new user 'weewx' would work, but they don't appear to.  You don't have to run the container with the "--privileged' option.

**Comment by LMSSonos** [comment]
@barndawgie - could you resolve the issue? I'm having the same issue. I did following

1) Created a user in synology `dockerweewx`
2) Logged in with ssh and run `id dockerweewx` to get the UID/GID
3) in the folder `/volume1/docker` created the `weewx` folder and also run `chmod 775` as suggested by @ksperow 
4) created docker-compose.yaml 

```
version: "3.8"

volumes:
  data:

services:
  weewx:
    image: felddy/weewx
    container_name: weewx    
    init: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /volume1/docker/weewx
        target: /data    
    environment:
      - TIMEZONE=US/Eastern
      - WEEWX_UID=1035      
      - WEEWX_GID=100
 ```

5) executed `sudo docker-compose up`

Following exception is shown
```
weewx    | Switching uid:gid to 1035:100
weewx    | Aug 13 14:16:30 syslogd started: BusyBox v1.30.1
weewx    | Aug 13 14:16:33 weewx[19] INFO __main__: Initializing weewx version 4.4.0
weewx    | Aug 13 14:16:33 weewx[19] INFO __main__: Using Python 3.9.1 (default, Jan 12 2021, 16:56:42)  [GCC 8.3.0]
weewx    | Aug 13 14:16:33 weewx[19] INFO __main__: Platform Linux-4.4.59+-x86_64-with-glibc2.28
weewx    | Aug 13 14:16:33 weewx[19] INFO __main__: Locale is 'C.UTF-8'
weewx    | Aug 13 14:16:33 weewx[19] INFO __main__: Using configuration file /data/weewx.conf
weewx    | Aug 13 14:16:33 weewx[19] INFO __main__: Debug is 0
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__: Caught unrecoverable exception:
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****  'unspecified'
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****  Traceback (most recent call last):
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****    File "/home/weewx/./bin/weewxd", line 151, in main
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 81, in __init__
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****      self.setupStation(config_dict)
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 103, in setupStation
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****      driver = config_dict[station_type]['driver']
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****    File "/opt/venv/lib/python3.9/site-packages/configobj.py", line 554, in __getitem__
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****      val = dict.__getitem__(self, key)
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****  KeyError: 'unspecified'
weewx    | Aug 13 14:16:33 weewx[19] CRITICAL __main__:     ****  Exiting.
weewx    | Traceback (most recent call last):
weewx    |   File "/home/weewx/./bin/weewxd", line 264, in <module>
weewx    |     main()
weewx    |   File "/home/weewx/./bin/weewxd", line 151, in main
weewx    |     engine = weewx.engine.StdEngine(config_dict)
weewx    |   File "/home/weewx/bin/weewx/engine.py", line 81, in __init__
weewx    |     self.setupStation(config_dict)
weewx    |   File "/home/weewx/bin/weewx/engine.py", line 103, in setupStation
weewx    |     driver = config_dict[station_type]['driver']
weewx    |   File "/opt/venv/lib/python3.9/site-packages/configobj.py", line 554, in __getitem__
weewx    |     val = dict.__getitem__(self, key)
weewx    | KeyError: 'unspecified'
```
weewx.config file is created and seems ok
docker-compose version: `docker-compose version 1.28.5, build 1bbbad71`
Synology: DS918+

**Comment by LMSSonos** [comment]
I found out the issue. the KeyError unspecified means that you need to edit the weewx.conf and change the station_type to the station you need. so not a docker related issue ;-)

**Comment by box99h** [comment]
@LMSSonos : May you comment how you edited the weewx.conf in a non running container?

**Comment by LMSSonos** [comment]
> @LMSSonos : May you comment how you edited the weewx.conf in a non running container?

The file is stored in  /volume1/docker/weewx folder so I can edit it anytime - this is configured in the docker-compose.yaml file

**Comment by box99h** [comment]
> > @LMSSonos : May you comment how you edited the weewx.conf in a non running container?
> 
> The file is stored in /volume1/docker/weewx folder so I can edit it anytime - this is configured in the docker-compose.yaml file

Thank you.

**Comment by barndawgie** [comment]
Resolving this as I've switched to a different model for getting these and don't ahve time to repro it.
