### ISSUE TITLE
Image generation doesn't work in v4

### ISSUE THREAD

**Issue by erozen** [felddy/weewx-docker#383]
# 🐛 Summary #

Per https://github.com/weewx/weewx/issues/974, image generation is broken in the current version (v4) of WeeWX.

An upgrade to version 5 of WeeWX is reported to fix the problem.

## To reproduce ##

Steps to reproduce the behaviour:

1. Run container
1. Watch logs, observe error.  Navigate to the landing page and note that images don't (re-)generate.
```
Traceback (most recent call last):
  File "/home/weewx/bin/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/home/weewx/bin/weewx/reportengine.py", line 385, in start
    self.run()
  File "/home/weewx/bin/weewx/imagegenerator.py", line 42, in run
    self.gen_images(self.gen_ts)
  File "/home/weewx/bin/weewx/imagegenerator.py", line 114, in gen_images
    image = plot.render()
            ^^^^^^^^^^^^^
  File "/home/weewx/bin/weeplot/genplot.py", line 212, in render
    self._renderBottom(draw)
  File "/home/weewx/bin/weeplot/genplot.py", line 404, in _renderBottom
    bottom_label_size = draw.textsize(self.bottom_label, font=bottom_label_font)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weewx/bin/weeplot/genplot.py", line 646, in textsize
    return ImageDraw.ImageDraw.textsize(self, string, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ImageDraw' has no attribute 'textsize'
```

## Expected behaviour ##

Images generate

**Comment by felddy** [comment]
This issue is probably not related to the containerization of WeeWX.  Let me know if this is fixed in the `v5` version of the container that was just released:
- https://github.com/felddy/weewx-docker/releases/tag/v5.1.0

**Comment by erozen** [comment]
I've upgraded to the latest container version, and can confirm that image generation now works.
There were a number of configuration changes to make, but nothing unsolvable.

Notably, there was a terminal error on my first attempt, logs showed:
```
2024-12-29 03:49:29 weewxd[7]: CRITICAL weewxd:     ****  ModuleNotFoundError: No module named 'user'

2024-12-29 03:49:29 weewxd[7]: CRITICAL weewxd:     ****  Exiting.
Traceback (most recent call last):
  File "/opt/venv/bin/weewxd", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/venv/lib/python3.13/site-packages/weewxd.py", line 121, in main
    engine = weewx.engine.StdEngine(config_dict)
  File "/opt/venv/lib/python3.13/site-packages/weewx/engine.py", line 89, in __init__
    self.loadServices(config_dict)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.13/site-packages/weewx/engine.py", line 157, in loadServices
    obj = weeutil.weeutil.get_object(svc)(self, config_dict)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/venv/lib/python3.13/site-packages/weeutil/weeutil.py", line 1404, in get_object
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'user'
```

Commenting out the `user.mqtt.MQTT` section of `restful_services` prevents the stackdump and allows startup, but I still get:
```
ERROR weeutil.startup: Cannot load user extensions: No module named 'user'
```
in my startup logs.  Possibly a `pip install` that needs to be run?

Happy for this ticket to close, let me know if you want more info on the `user` issue.

**Comment by felddy** [comment]
> ```
> ERROR weeutil.startup: Cannot load user extensions: No module named 'user'
> ```

I see this in my logs as well.  I think it can be safely ignored.  It is generated by WeeWX trying, and failing, to load a package named `user.extensions`: 
- https://github.com/weewx/weewx/blob/1566a768af0963a43bd1c7b174293c46226a7fb5/src/weeutil/startup.py#L78

The `weectl station create` command will create these.  If you start the container with an empty `data` volume it will do this for you.  Then move `bin` to your actual `data` directory.  

```console
➤ find data/bin
data/bin
data/bin/user
data/bin/user/__init__.py
data/bin/user/extensions.py
```
